spring:
  rabbitmq:
    host: 192.168.6.100
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: none
        prefetch: 5           # 预抓取5个
#        retry:
#          enabled: true
#          max-attempts: 2
#          initial-interval: 2000
#          max-interval: 5000
#          multiplier: 2
